## **DAY-14:-**

```
Numpy

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6,7,8,9]

```
array:-

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

```
asarray:-

In [7]:
a=[1,2,34]
np.asarray(a)

array([ 1,  2, 34])

```
matrix:-

In [10]:
b=np.matrix([[1,2,3,4]])
b

matrix([[1, 2, 3, 4]])

```
asanyarray:-

In [11]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

```
fromfunction:-

In [12]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

```
fromiter:-

In [13]:
iterable=(i*i for i in range(5))

In [14]:
iterable

<generator object <genexpr> at 0x000002955F46A670>

In [16]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

```
fromstring:-

In [17]:
np.fromstring("234 234",sep=" ")

array([234., 234.])

In [18]:
np.fromstring("234 234",sep=",")

C:\Users\Abhi\AppData\Local\Temp\ipykernel_21948\3300294027.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("234 234",sep=",")


array([234.])

```
Data Type in Numpy:-

In [20]:
l=[1,2,3,4,5,6]
arr=np.array(l)

In [22]:
np.ndim(arr)

1

In [25]:
arr1=np.array([l,l])

In [26]:
np.ndim(arr1)

2

In [27]:
arr.shape

(6,)

In [28]:
arr1.shape

(2, 6)

In [29]:
arr.dtype

dtype('int32')

In [30]:
arr1.dtype

dtype('int32')

In [33]:
arr2=np.array([[1.4,2.4,4.5],[1,2,3]])

In [35]:
arr2.dtype

dtype('float64')

```
arange:-

In [38]:
np.arange(0.4,13.5,.3)

array([ 0.4,  0.7,  1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,
        3.7,  4. ,  4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,
        7. ,  7.3,  7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7, 10. ,
       10.3, 10.6, 10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7, 13. , 13.3])

```
linspace:-

In [39]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

```
zeros:-

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [46]:
np.ones((2,3))*4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [54]:
arr=np.random.randn(3,4)

In [55]:
import pandas as pd

In [56]:
pd.DataFrame(arr)

0         1         2         3
0 -0.539127 -0.169556 -2.767438  0.532408
1 -0.476535  0.932141 -0.787735  0.385393
2  1.202676 -0.741091  0.931088  0.559360

In [63]:
pd.DataFrame(np.random.rand(3,4))

0         1         2         3
0  0.268363  0.318281  0.328183  0.665665
1  0.398848  0.264170  0.826828  0.394807
2  0.026968  0.184456  0.113012  0.276412

In [65]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv")

In [66]:
arr=np.random.rand(3,4)

In [67]:
arr

array([[0.37739834, 0.50695578, 0.19971435, 0.26848278],
       [0.53994911, 0.80179537, 0.75215562, 0.02699398],
       [0.81428494, 0.2711066 , 0.22156961, 0.06801037]])

In [71]:
arr=arr.reshape(6,2)

In [72]:
arr[1][1]

0.2684827816038434

In [79]:
arr[arr>0.1]

array([0.37739834, 0.50695578, 0.19971435, 0.26848278, 0.53994911,
       0.80179537, 0.75215562, 0.81428494, 0.2711066 , 0.22156961])

In [83]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [85]:
arr1

array([[3, 2, 9],
       [6, 3, 2],
       [1, 2, 3]])

In [86]:
arr2

array([[4, 9, 9],
       [3, 4, 3],
       [6, 8, 8]])

In [88]:
arr1+arr2

array([[ 7, 11, 18],
       [ 9,  7,  5],
       [ 7, 10, 11]])

In [89]:
arr1*arr2

array([[12, 18, 81],
       [18, 12,  6],
       [ 6, 16, 24]])

```
 Numpy part-2:-

In [90]:
import numpy as np

In [93]:
arr=np.random.randint(1,10,(3,4))

In [94]:
arr

array([[5, 7, 6, 4],
       [7, 1, 9, 1],
       [9, 7, 7, 4]])

In [95]:
arr.reshape(6,2)

array([[5, 7],
       [6, 4],
       [7, 1],
       [9, 1],
       [9, 7],
       [7, 4]])

In [96]:
arr.reshape(2,6)

array([[5, 7, 6, 4, 7, 1],
       [9, 1, 9, 7, 7, 4]])

In [97]:
arr.T

array([[5, 7, 9],
       [7, 1, 7],
       [6, 9, 7],
       [4, 1, 4]])

In [98]:
arr.flatten()

array([5, 7, 6, 4, 7, 1, 9, 1, 9, 7, 7, 4])

In [99]:
arr1=np.array([1,2,3,3,4])

In [100]:
arr1.ndim

1

In [101]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [102]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [104]:
np.squeeze(arr)

array([[5, 7, 6, 4],
       [7, 1, 9, 1],
       [9, 7, 7, 4]])

In [105]:
np.diag(arr)

array([5, 1, 7])

```
Binary Operation:-

In [106]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [109]:
arr1+arr2

array([[17, 18, 12,  8],
       [ 9, 15,  8, 14],
       [16,  7, 11, 10]])

In [110]:
arr1*arr2

array([[72, 81, 27, 12],
       [ 8, 56,  7, 45],
       [63,  6, 18, 24]])

In [112]:
arr1-arr2

array([[ 1,  0,  6, -4],
       [-7, -1,  6,  4],
       [-2, -5,  7,  2]])

In [113]:
arr%arr2

array([[5, 7, 0, 4],
       [7, 1, 0, 1],
       [0, 1, 1, 0]])

In [115]:
arr1**arr2

array([[ 43046721, 387420489,       729,        64],
       [        1,   5764801,         7,     59049],
       [ 40353607,         1,        81,      1296]])

In [118]:
arr1

array([[9, 9, 9, 2],
       [1, 7, 7, 9],
       [7, 1, 9, 6]])

In [119]:
arr2

array([[8, 9, 3, 6],
       [8, 8, 1, 5],
       [9, 6, 2, 4]])

In [120]:
~arr1

array([[-10, -10, -10,  -3],
       [ -2,  -8,  -8, -10],
       [ -8,  -2, -10,  -7]])

In [121]:
arr1|arr2

array([[ 9,  9, 11,  6],
       [ 9, 15,  7, 13],
       [15,  7, 11,  6]])

```
Numpy string Function:-

In [124]:
arr=np.array(["Abhishek","Upadhyay"])

In [127]:
np.char.upper(arr)

array(['ABHISHEK', 'UPADHYAY'], dtype='<U8')

In [128]:
np.char.title(arr)

array(['Abhishek', 'Upadhyay'], dtype='<U8')

```
Numpy part-3:-

```
Sorting,Searching & Counting Function:-

In [131]:
arr=np.array([1,2,3,4,5,6,7,5,4,3,5,3,4,10,11,12,13])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  5,  4,  3,  5,  3,  4, 10, 11, 12, 13])

In [133]:
np.sort(arr)

array([ 1,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  7, 10, 11, 12, 13])

In [140]:
np.searchsorted(arr,34)

17

In [141]:
np.where(arr>4)

(array([ 4,  5,  6,  7, 10, 13, 14, 15, 16], dtype=int64),)