## PCA Implimentation:-

In [9]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.decomposition import PCA
from sklearn import datasets

In [10]:
dataset=datasets.load_iris()

In [11]:
x=dataset["data"]
y=dataset["target"]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [13]:
pca=PCA(n_components=3)

In [14]:
x_train

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2

In [15]:
x_train=pca.fit_transform(x_train)

In [16]:
x_train

array([[-3.17191553e+00,  1.29457045e-01,  2.74955159e-01],
       [-2.34745821e+00,  1.33781523e+00,  2.71788068e-01],
       [ 9.71520952e-01,  4.86044204e-01, -3.20689648e-01],
       [-2.56753356e+00,  1.60522934e-02,  8.62344384e-02],
       [-2.95088792e+00, -3.43587883e-01,  1.72320523e-01],
       [ 1.57397400e+00, -3.56283392e-01, -1.34399639e-01],
       [ 9.76313730e-01,  3.35516537e-01, -2.45953936e-02],
       [-2.51851294e+00,  3.69738445e-01, -9.24482207e-02],
       [-2.68502537e+00,  3.26991300e-01,  7.57370407e-02],
       [-2.60734589e+00,  8.14321255e-01,  2.16884159e-01],
       [ 1.46242806e+00, -5.57915855e-01,  2.83802576e-01],
       [ 8.50516252e-01,  2.08313940e-01,  3.81872802e-01],
       [ 1.26454870e+00,  4.27647245e-01, -2.42585185e-01],
       [-2.58248688e+00,  8.09432716e-01,  1.26361388e-01],
       [-2.46440403e+00,  6.47300146e-01, -8.69320372e-02],
       [-1.40580297e-01, -6.65638257e-01, -3.23323589e-01],
       [ 1.49066461e+00, -1.21522133e-01

In [17]:
pca.components_

array([[ 0.35922175, -0.08867716,  0.85800365,  0.35626652],
       [ 0.66072216,  0.72708635, -0.16688652, -0.08331002],
       [-0.5781132 ,  0.60569412,  0.08006791,  0.54084091]])

In [28]:
pca.explained_variance_

array([4.15384465, 0.25811933, 0.08303984])

In [25]:
pca.explained_variance_ratio_

array([0.91959926, 0.05714377, 0.01838378])

In [26]:
pca.get_covariance()

array([[ 0.67865476, -0.03956162,  1.24462745,  0.49670868],
       [-0.03956162,  0.20171148, -0.34006162, -0.12484594],
       [ 1.24462745, -0.34006162,  3.07071148,  1.26893557],
       [ 0.49670868, -0.12484594,  1.26893557,  0.56593838]])

In [27]:
pca.get_feature_names_out()

array(['pca0', 'pca1', 'pca2'], dtype=object)